"""empty message

Revision ID: 046596a52d7f
Revises: e72b60792e81
Create Date: 2024-10-31 16:05:39.576532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '046596a52d7f'
down_revision = 'e72b60792e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Email_Autorizado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('DOCENTE', 'REPRESENTANTE', 'ADMINISTRADOR', name='roles'), nullable=False))
        batch_op.drop_column('Role')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('DOCENTE', 'REPRESENTANTE', 'ADMINISTRADOR', name='roles'), nullable=False))
        batch_op.drop_column('Role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Role', postgresql.ENUM('DOCENTE', 'REPRESENTANTE', 'ADMINISTRADOR', name='roles'), autoincrement=False, nullable=False))
        batch_op.drop_column('role')

    with op.batch_alter_table('Email_Autorizado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Role', postgresql.ENUM('DOCENTE', 'REPRESENTANTE', 'ADMINISTRADOR', name='roles'), autoincrement=False, nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
