"""empty message

Revision ID: 20253fdb547a
Revises: e643c15b88a3
Create Date: 2024-11-05 01:39:14.966061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20253fdb547a'
down_revision = 'e643c15b88a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estudiante_materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_materia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_estudiante', 'id_materia', name='estudiante_materia_unique')
    )
    op.drop_table('aula_alumnos')
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grado', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'grado', ['grado'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grado')

    op.create_table('aula_alumnos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aula_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estudiante_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], name='aula_alumnos_aula_id_fkey'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], name='aula_alumnos_estudiante_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='aula_alumnos_pkey'),
    sa.UniqueConstraint('aula_id', 'estudiante_id', name='aula_id_estudiante_id_unique')
    )
    op.drop_table('estudiante_materias')
    op.drop_table('grado')
    # ### end Alembic commands ###
