"""empty message

Revision ID: 63202d1366b1
Revises: 4fab7fe6c24f
Create Date: 2024-09-20 01:04:27.503403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63202d1366b1'
down_revision = '4fab7fe6c24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('developer',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.alter_column('developer',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.alter_column('game_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)

    # ### end Alembic commands ###
