"""empty message

Revision ID: 8c038d54f12b
Revises: d7f28c686946
Create Date: 2024-11-06 17:11:26.406414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c038d54f12b'
down_revision = 'd7f28c686946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.create_unique_constraint('estudiante_representante_unique', ['nombre', 'apellido', 'representante_id'])

    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grado_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('materia_grado_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'grado', ['grado_id'], ['id'])
        batch_op.drop_column('grado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grado', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('materia_grado_fkey', 'grado', ['grado'], ['id'])
        batch_op.drop_column('grado_id')

    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.drop_constraint('estudiante_representante_unique', type_='unique')

    # ### end Alembic commands ###
