"""empty message

Revision ID: 9d9701975e4a
Revises: 32868a767b23
Create Date: 2024-10-22 23:08:14.316545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d9701975e4a'
down_revision = '32868a767b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reparacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnostico', sa.String(length=200), nullable=True))
        batch_op.alter_column('fallas',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('DTC',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('solucion',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('fecha_ingreso',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('fecha_reparacion',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('costo_reparacion',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('reporte',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reparacion', schema=None) as batch_op:
        batch_op.alter_column('reporte',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('costo_reparacion',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('fecha_reparacion',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('fecha_ingreso',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('solucion',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('DTC',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('fallas',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('diagnostico')

    # ### end Alembic commands ###
