"""empty message

Revision ID: d7f28c686946
Revises: ff572702c5d5
Create Date: 2024-11-05 01:57:40.195125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f28c686946'
down_revision = 'ff572702c5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.drop_column('nota')

    # ### end Alembic commands ###
