"""empty message

Revision ID: ff572702c5d5
Revises: 20253fdb547a
Create Date: 2024-11-05 01:40:37.150482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff572702c5d5'
down_revision = '20253fdb547a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aula')
    with op.batch_alter_table('evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalizada', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluacion', schema=None) as batch_op:
        batch_op.drop_column('finalizada')

    op.create_table('aula',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('docente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], name='aula_docente_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='aula_pkey')
    )
    # ### end Alembic commands ###
